### PR TITLE
Preserve the visibility of buttons when scrolling.

### PR DESCRIPTION
**Pull request by yrammos**
Introduces CSS improvements, and tiny JS tweaks, to ensure the visibility of buttons when scrolling and to place them in more ergonomic positions.

### CODE REVIEW

**Comment by yrammos** [comment]
(Testing tip: add a few views/layers and resize the browser window until scrolling is necessary, both top-down and left-right, to view the score in its entirety.)

**Comment by yrammos** [comment]
Working well on Chrome but not on Firefox.

**Comment by yrammos** [comment]
Should now work on Firefox, albeit not exactly as on Chrome (specifically, the `.view_buttons` are not sticky horizontally).

**Comment by yrammos** [comment]
Also added padding after the last layer div, to prevent overlaps with the bottom panel of buttons.

**Comment by yrammos** [comment]
This can be improved. Freezing temporarily, until time permits.

**Comment by yrammos** [comment]
Should now be working as intended across browsers.

**Review by pettter — APPROVED** [review]
LGTM, and tests pass

**Pull request merged**
