### PR TITLE
Drag select

### PR DESCRIPTION
**Pull request by yrammos**
Implements a "lasso" tool for drag-selecting relations.

### CODE REVIEW

**Comment by yrammos** [comment]
Marking as draft — small improvement coming up soon.

**Comment by yrammos** [comment]
Should be working as intended now.

**Comment by pettter** [comment]
Is it possible to switch this between selecting notes and relations somehow? Maybe have it select relations by default, but switch to drag-selecting notes if a note has been selected or so?

**Comment by yrammos** [comment]
Yes, I thought about that and played around with it a little. There were some bugs in the upstream library that got in the way but I might be able to circumnavigate them.

Will give it a second look.

**Comment by yrammos** [comment]
Following the latest commits, the lasso now selects:

- relations, if the selection list is initially empty;
- notes, if the  selection list is initially empty and the user presses <kbd>Shift</kbd> while dragging;
- items of the same type as any previously selected items.

**Review by pettter — APPROVED** [review]

**Pull request merged**
