### PR TITLE
Say goodbye to the old gearbox menu

### LINKED ISSUE #148: UI: Style the main menu
The gearbox menu should be styled according to the Figma.

### PR DESCRIPTION
**Pull request by meduzen**
Closes #148.

Done:
- [x] Relation width control.
- [x] The 3 controls toggling stems, shades and non-related tones (+ their keyboard shortcuts). It seems the non-related tones can’t be reversed once clicked (not sure it’s a bug or intended, but it’s the same on the [online version](https://dcmlab.github.io/reductive_analysis_app/index.html)).

Still to-do for this issue:
- [x] The audio player (which was proto-prototyped a while ago):
  - [x] player styles and interactivity.
  - [x] alternate between play and pause icons instead of having them separately (+ get rid of the volume button)
- [x]  Know when to collapse the menu when all options are visible. I’m thinking about combining:
  -  [x] a timeout: the menu could auto-hide after X seconds of inactivity;
  -  [x] immediate closing when interacting outside anywhere outside its area.
-  [x] There’s apparently a new bug with the shades: relations get gray-ish when first toggling the shades for the alternates colors, then resizing the relation width, then toggling again to the regular colors.

### CODE REVIEW

**Comment by meduzen** [comment]
👋  @pettter @yrammos

Comments and questions regarding the audio player, which looks like this in the design file:

image

1. I plan to “merge” the two play and pause buttons into one, and toggle the icon depending on the playing state.
2. Is currently “mute volume” a needed feature, assuming people won’t click play and then mute?
3. In the early prototype, I had a “stop” button (screenshot below, from current state of this PR), which is handy to reset the timeline to the beginning of the track. Any objection to keep it (if we drop the volume one)?
image

**Comment by yrammos** [comment]
@meduzen I agree on all three changes you propose. Thanks a lot.

**Comment by pettter** [comment]
@meduzen I agree with @yrammos, all three changes sound good to me. Nice work!

One thing I'm noticing as I play around with it is that the piano sound seems to do all sustain all the time - I'm going to have a look at the player library and see if I can find some option to make it take note lengths into account.

**Comment by pettter** [comment]
I added some code to stop the sample playback (hopefully) appropriately. For me it seems to work, but please have a look at the commit, and feel free to revert it if it looks off to you.

**Comment by yrammos** [comment]
One issue plus a couple of thoughts:

- [ ] The widget is silent on Safari. All its visuals do work, but no sound is actually output...
- [ ] Many MEI/MusicXML files do not include tempo data, for better or worse, and the default tempo can be entirely inappropriate, sometimes to the point of incomprehensibility (e.g. Schubert's _Gute Nacht_ from the corpus). Do you think we could tuck in a tempo adjustment control in the widget?
- [ ] Wouldn't it make sense to play the currently active layer (reduction) rather always playing the original music? Obviously this would be a low-priority feature or even a v2 feature. @pettter

**Comment by pettter** [comment]
OK, in turn:

 * That's a bit strange - I'll go look if it's a known issue with either midi-player-js or sample-player
 * Codewise, it's possible, I think, but I'm not sure of the best way to add it to the UI. A pop-up slider perhaps?
 * There's a button in the layer menu for playing the current reduction in that layer, but maybe that should indeed be the default behaviour, with the fallback to the original if no layer is "current". I'm not sure, honestly, but I see what you mean.

**Comment by pettter** [comment]
Yep, looks like it might be a known Safari problem: https://github.com/danigb/soundfont-player/issues/81

**Comment by yrammos** [comment]
> That's a bit strange - I'll go look if it's a known issue with either midi-player-js or sample-player

Thanks for looking at the upstream repo, @pettter. Let's  just wait then until Safari and/or the library are updated to resolve the issue.

> Codewise, it's possible, I think, but I'm not sure of the best way to add it to the UI. A pop-up slider perhaps?

A pop-up slider would be ideal, unless @meduzen has alternative ideas. I will go ahead and create a low-priority issue.

> There's a button in the layer menu for playing the current reduction in that layer, but maybe that should indeed be the default behaviour, with the fallback to the original if no layer is "current". I'm not sure, honestly, but I see what you mean.

Indeed there is — I never ever use the playback feature, and it shows… 

Alternatively, we could have a checkbox in the playback widget to toggle between current layer and initial score (layer 0).

**Comment by meduzen** [comment]
Finally catching up all the stuff!

## Safari sound issue

I don’t have the sound issue in Safari 15.2 (build 16612.3.6.1.8, 16612, released December 13), but I have it in Safari Technology Preview (the “in-development” version of Safari) 137 (Safari 15.4, WebKit 16613.1.11.8). Let’s hope they fix it in next Safari release

## @pettter ’s fix for playback

Well done. 👍 

I managed to have an error thrown will trying to pause or stop a note that wasn’t in the `activeNotes` object. Note velocity was at `0`when the event fired. So I added a condition (using `?. stop()` instead of `.stop`) to fix this:

```js
TypeError: this.activeNotes[(event.noteName + event.track)] is undefined
```

## Reduction playing

A checkbox near the player seems a nice idea to me. I suggest we leave it as planned for now (screenshot below), then we’ll see how to integrate/design the changes for both reduction playing and the tempo (#186).

image

**Comment by meduzen** [comment]
Aside from the following one, everything is done:

> There’s apparently a new bug with the shades: relations get gray-ish when first toggling the shades for the alternates colors, then resizing the relation width, then toggling again to the regular colors.

Gonna check later today.

**Comment by meduzen** [comment]
Merging!

**Comment by pettter** [comment]
Nice work!

**Pull request merged**
