### PR TITLE
First set of tests, using Jest and Puppeteer

### PR DESCRIPTION
**Pull request by pettter**
This is the first set of tests for the testing framework. It can be run using "jest" or "npm test" after "npm ci" has set up the requisite Node modules.

### CODE REVIEW

**Comment by pettter** [comment]
Not quite what I want.

**Comment by yrammos** [comment]
Would you care to elaborate?

**Comment by pettter** [comment]
@yrammos I forgot to do a merge from master first, so there were a bunch of unclear things going on in the PR. E.g. this one says it does changes to 14 files, whereas the one after merging from master (#50) only changes five files, making it much more obvious what is actually included and not in this PR.

**Comment by yrammos** [comment]
@pettter, I see. Do you think this warrants a `git-revert`? Apparently GitHub now provides a [revert button][https://github.com/DCMLab/reductive_analysis_app/pull/50) directly on the PR. I wasn't aware.

**Pull request closed without merging**
