### PR TITLE
Add layer menu

### LINKED ISSUE #149: UI: Style the layer menu
The layer menu should be styled according to the Figma.

### PR DESCRIPTION
**Pull request by meduzen**
Closes #149.

Draft PR so you can check if it works as expected on MEI side. Don’t forget to `npm i`.

### CODE REVIEW

**Comment by yrammos** [comment]
@meduzen thank you for this. I didn't notice any MEI-side bugs but this is something we could test better with formal testing. It's a bit difficult to review the actual code because of the large number of (irrelevant?) file changes e.g. in the build system. The direction of the changes looks good to me, along the lines of our Sunday discussion. Thanks again.

**Comment by pettter** [comment]
I looked through the specific commits and it all looks entirely reasonable to me. Thanks!

**Comment by yrammos** [comment]
Oops this is a series of atomic commits — thanks for pointing out the obvious I missed, @pettter. This looks clear indeed, @meduzen, thanks.

**Comment by pettter** [comment]
I removed various specific versions of `esbuild` from `package-lock.json` since `npm i` didn't run on non-mac computers, as far as I could tell.

**Comment by pettter** [comment]
This seems like it works now. Anything else that needs doing before merging into `ui`?

**Pull request merged**
