### PR TITLE
Fix 'tooltip is undefined' errors.

### PR DESCRIPTION
**Pull request by pettter**
When testing I get errors that "tooltip is undefined" when trying to scroll through relations. This fixes those errors, but I'm not sure if the tooltip is actually restored..

Also I'm not sure if jbox should be added to packages.json or somesuch - feel free to add on to this branch to get it to a proper state.

### CODE REVIEW

**Comment by meduzen** [comment]
Indeed I removed jBox a bit prematurely. Thanks for the PR!

This makes me think we don’t have a design fo the tooltip, yet. Not a priority, but adding this to my list of stuff to check with the designer.

**Review by meduzen — APPROVED** [review]

**Comment by pettter** [comment]
Well, prematurely or incompletely ;)

Right, to get it more consistent with the rest of the app? I think it's already not that far off, right? Could it be enough to just change the font to the same as the other text?

**Comment by meduzen** [comment]
Yes, that’ll likely require minor visual tweaks, but I’ll also make it more performant: right now it follows the cursor by changing `top` and `left` values, which may cause perf issues because changing them implies the browser needs to recompute the layout.

Generally, there are only two safe values to change to preserve good performances in CSS: `opacity` and `transform`. These two doesn’t involve recomputation of the full layout but only of the affected elements. (It’s the short version. There are a lot of additional nuances.)

**Comment by pettter** [comment]
Ah gotcha, that's good to know. Thanks!

**Pull request merged**
